<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_robot">

  <xacro:include filename="$(find demo_diff_robot)/urdf/material_common.xacro"/>
  <xacro:include filename="$(find demo_diff_robot)/urdf/inertial_common.xacro"/>
  
  <xacro:macro name="diff_robot" params="prefix">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.3"/>
    <xacro:property name="base_length" value="0.1"/>
    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.3"/>
    <xacro:property name="wheel_length" value="0.020"/>
    <xacro:property name="wheel_radius" value="0.015"/>
    <xacro:property name="caster_wheel_mass" value="0.1"/>
    <xacro:property name="caster_wheel_radius" value="0.015"/>

    <!-- dummy link -->
    <link name="${prefix}dummy_link">
    </link>

    <joint name="${prefix}dummy_joint" type="fixed">
      <parent link="${prefix}dummy_link"/>
      <child link="${prefix}base_link"/>
      <origin xyz="0 0 ${base_height/2+wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- base link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"/>
    </link>

    <gazebo reference="${prefix}base_link">
      <material>Gazebo/Orange</material>
    </gazebo>

    <!-- left wheel link -->
    <link name="${prefix}left_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}left_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- left wheel joint -->
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel_link"/>
      <origin xyz="0 ${base_width/2} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- right wheel link -->
    <link name="${prefix}right_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}right_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- right wheel joint -->
    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel_link"/>
      <origin xyz="0 -${base_width/2} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- front caster wheel link -->
    <link name="${prefix}front_caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_wheel_radius}"/>
    </link>

    <!-- front caster wheel joint -->
    <joint name="${prefix}front_caster_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_caster_wheel_link"/>
      <origin xyz="${base_length/2 - caster_wheel_radius} 0 -${base_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- back caster wheel link -->
    <link name="${prefix}back_caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_wheel_radius}"/>
    </link>

    <!-- back caster wheel joint -->
    <joint name="${prefix}back_caster_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}back_caster_wheel_link"/>
      <origin xyz="${-base_length/2 + caster_wheel_radius} 0 -${base_height/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:diff_robot prefix=""/>

</robot>
