<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_robot">

  <xacro:include filename="$(find demo_diff_robot)/urdf/material_common.xacro"/>
  <xacro:include filename="$(find demo_diff_robot)/urdf/inertial_common.xacro"/>
  <xacro:include filename="$(find demo_diff_robot)/urdf/diff_robot_ros2_control.xacro"/>
  
  <xacro:macro name="diff_robot" params="prefix">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.3"/>
    <xacro:property name="base_length" value="0.1"/>
    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="lidar_mass" value="0.03"/>
    <xacro:property name="lidar_length" value="0.01"/>
    <xacro:property name="lidar_radius" value="0.01"/>
    <xacro:property name="wheel_mass" value="0.3"/>
    <xacro:property name="wheel_length" value="0.020"/>
    <xacro:property name="wheel_radius" value="0.015"/>
    <xacro:property name="caster_wheel_mass" value="0.1"/>
    <xacro:property name="caster_wheel_radius" value="0.015"/>

    <!-- dummy link -->
    <link name="${prefix}dummy_link">
    </link>

    <!-- dummy joint -->
    <joint name="${prefix}dummy_joint" type="fixed">
      <parent link="${prefix}dummy_link"/>
      <child link="${prefix}base_link"/>
      <origin xyz="0 0 ${base_height/2+wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- base link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"/>
    </link>

    <gazebo reference="${prefix}base_link">
      <material>Gazebo/Orange</material>
    </gazebo>

    <!-- imu link -->
    <link name="${prefix}imu_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.01" l="0.01" w="0.01" h="0.01"/>
    </link>

    <gazebo reference="${prefix}imu_link">
      <material>Gazebo/Red</material>
      <sensor name="imu_sensor" type="imu">
        <plugin name="imu_sensor" filename="libgazebo_ros_imu_sensor.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/out:=/imu</remapping>
          </ros>
          <initial_orientation_as_reference>false</initial_orientation_as_reference>
        </plugin>
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
      </sensor>
    </gazebo>

    <!-- imu joint -->
    <joint name="${prefix}imu_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- lidar link -->
    <link name="${prefix}lidar_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${lidar_mass}" l="${lidar_length}" r="${lidar_radius}"/>
    </link>

    <gazebo reference="${prefix}lidar_link">
      <material>Gazebo/Red</material>
      <sensor name="lidar_sensor" type="ray">
        <plugin name="lidar_sensor" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/out:=/scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>lidar_link</frame_name>
        </plugin>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>-${PI}</min_angle>
              <max_angle>${PI}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.03</min>
            <max>5</max>
            <resolution>0.003</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
      </sensor>
    </gazebo>

    <!-- lidar joint -->
    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}lidar_link"/>
      <origin xyz="0 0 ${base_height/2 + lidar_length/2}" rpy="0 0 0"/>
    </joint>

    <!-- left wheel link -->
    <link name="${prefix}left_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}left_wheel_link">
      <material>Gazebo/Black</material>
      <mu1 value="20.0"/>
      <mu2 value="20.0"/>
      <kp value="1000000000.0"/>
      <kd value="1.0"/>
    </gazebo>

    <!-- left wheel joint -->
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel_link"/>
      <origin xyz="0 ${base_width/2} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- right wheel link -->
    <link name="${prefix}right_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}right_wheel_link">
      <material>Gazebo/Black</material>
      <mu1 value="20.0"/>
      <mu2 value="20.0"/>
      <kp value="1000000000.0"/>
      <kd value="1.0"/>
    </gazebo>

    <!-- right wheel joint -->
    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel_link"/>
      <origin xyz="0 -${base_width/2} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- front caster wheel link -->
    <link name="${prefix}front_caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}front_caster_wheel_link">
      <mu1 value="0.0"/>
      <mu2 value="0.0"/>
      <kp value="1000000000.0"/>
      <kd value="1.0"/>
    </gazebo>

    <!-- front caster wheel joint -->
    <joint name="${prefix}front_caster_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_caster_wheel_link"/>
      <origin xyz="${base_length/2 - caster_wheel_radius} 0 -${base_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- back caster wheel link -->
    <link name="${prefix}back_caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_wheel_radius}"/>
    </link>

    <gazebo reference="${prefix}back_caster_wheel_link">
      <mu1 value="0.0"/>
      <mu2 value="0.0"/>
      <kp value="1000000000.0"/>
      <kd value="1.0"/>
    </gazebo>

    <!-- back caster wheel joint -->
    <joint name="${prefix}back_caster_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}back_caster_wheel_link"/>
      <origin xyz="${-base_length/2 + caster_wheel_radius} 0 -${base_height/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:diff_robot prefix=""/>
  <xacro:diff_robot_ros2_control/>

</robot>
